[package]
name = "dnd_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
serde = { version = "1.0.228", features = ["derive"] }
surrealdb = { version = "2.3.10", features = ["kv-rocksdb"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
